spring:
  sql:
    init:
      mode: always

  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      show_sql: true
      format_sql: true
      ddl-auto: create
    defer-datasource-initialization: true

gemini:
  baseurl: https://generativelanguage.googleapis.com

googleai:
   api:
    key: ${GEMINI_API_KEY}

klaytn:
  api:
    base-url: https://wallet-api.klaytnapi.com/v2
    account-endpoint: /account
    contract-endpoint: /contract/babsim/token
    contract-address-or-alias: babsim

  auth:
    x-chain-id: 1001
    authorization: Basic S0FTS1FNTVlaV1lOTzJJUDlWNEVSQ1RaOjdEUHg3M0IzWFZsaS05NjRRTVZGV0Y0WjNCODctWm9IQk9fMmhTRkE=



